# Configuration for Fly.io deployment
# This file tells Fly.io how to build and run your NestJS application

app = "bailar-api"  # Replace with your Fly.io app name if different
primary_region = "cdg"  # Paris region

[build]
  # Use the Dockerfile in the same directory
  dockerfile = "Dockerfile"
  # Build arguments if needed
  [build.args]
    NODE_ENV = "production"

[deploy]
  # Command to run migrations before starting the app
  release_command = "pnpm run typeorm migration:run"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.processes]]
    script = "node dist/main.js"
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0
